name: we_yapping_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.2.0+3
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  image_picker: ^1.0.8
  get: ^4.6.6

  socket_io_client: ^3.0.0
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  animated_text_kit: ^4.2.2
  supabase_flutter: ^2.8.3
  file_picker: ^8.0.0+1
  open_file: ^3.3.2
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

  fonts:
    - family: Work_Sans
      fonts:
        - asset: assets/fonts/Work_Sans/static/WorkSans-Regular.ttf
        - asset: assets/fonts/Work_Sans/static/WorkSans-Italic.ttf
          style: italic
        - asset: assets/fonts/Work_Sans/static/WorkSans-Bold.ttf
          weight: 700
